# Generated by Django 5.1.1 on 2025-07-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriprion',
            new_name='description',
        ),
    ]
